### ISSUE TITLE
[BUG] @repeat_every() does not run without @app.on_event('startup') decorator

### ISSUE THREAD

**Issue by caseyjohnsonwv** [dmontagu/fastapi-utils#256] opened 2022-04-05 06:06 UTC
**Describe the bug**
The `@repeat_every()` decorator does not trigger the function it decorates unless the `@app.on_event('startup')` decorator is also present.

**To Reproduce**
I created this sample `main.py` to show the issue I've been seeing.
1. Copy the below and run `python3 main.py`. The app will create a local file `test.txt` and write a Unix timestamp to it every second.
2. Stop the app and comment out `@app.on_event('startup')`
3. Run the app again. The file `test.txt` is no longer being updated. If you delete this file and restart the app, it will never be created.
```
import time
from fastapi import FastAPI
from fastapi_utils.tasks import repeat_every
import uvicorn

app = FastAPI()

@app.on_event('startup')
@repeat_every(seconds=1)
def do_something():
    with open('test.txt', 'w') as f:
        f.write(f"{time.time():.0f}")

if __name__ == '__main__':
    uvicorn.run('main:app')
```

**Expected behavior**
The function `do_something()` should be writing to the file every 1 second, even with `@app.on_event('startup')` commented out.

**Environment:**
 - OS: Windows 10
 - FastAPI Utils: 0.2.1
 -  FastAPI: 0.75.0
 - Pydantic: 1.9.0
- Python: 3.10.4

**Comment by clemens-tolboom** [comment] 2022-06-19 10:19
I can confirm this. Even swapping the two

from (working)
```python
@app.on_event('startup')
@repeat_every(seconds=1)
```
into (prints once)
```python
@repeat_every(seconds=1)
@app.on_event('startup')
```

I changed the test into

```python
from fastapi import FastAPI
from fastapi_utils.tasks import repeat_every
import uvicorn

app = FastAPI()

@app.on_event('startup')
@repeat_every(seconds=0.1, max_repetitions=80)
def do_something():
    print(".", end='')

if __name__ == '__main__':
    uvicorn.run(app)
```

**Comment by vkomodey** [comment] 2022-08-11 11:44
the same here. works only with startup event

**Comment by mvoitko** [comment] 2022-09-21 13:01
I we don't use `@app.on_event('startup')` how do the app know when to start the task?

**Comment by lennpet** [comment] 2022-12-03 07:08
My suggestion would be that the framework scans for all decorator @repeat_every at startup and call them, preferable after that all @app.on_event("startup") has been executed. Comparing with Spring framework that has @scheduled that does exactly the same. Where you can decorate multiple functions/tasks that will be called on at startup. @scheduled decorator can also be configured with an initial delay, that is very nice to have.

**Comment by znstahl** [comment] 2023-02-24 08:07
> I we don't use `@app.on_event('startup')` how do the app know when to start the task?

The whole point of writing APIs in frameworks like FastAPI is for them to be opinionated. 
It's also pretty standard for scheduling frameworks to allow specifying a schedule without explicitly specifying a start time, which then by convention equals to "whenever you can start it ASAP".

It's also pretty pointless to require multiple decorators if one of them will be followed by the other in 99,9% (if not 100%) of the cases.

**Comment by caseyjohnsonwv** [comment] 2023-02-28 00:54
> I we don't use `@app.on_event('startup')` how do the app know when to start the task?

> It's also pretty pointless to require multiple decorators if one of them will be followed by the other in 99,9% (if not 100%) of the cases.

I think a great example of this in practice is Apache Airflow, which requires a `datetime` object to specify the earliest invocation. This datetime can be in the past, meaning "start this as soon as possible." It would make sense for the framework to do one or both of the following:
- Infer `@repeat_every()` to mean "start immediately" when not following another decorator.
- Explicitly require a `datetime` object inside of `@repeat_every()` to specify the first invocation.

**Comment by clemens-tolboom** [comment] 2023-03-02 09:02
'decorators are wrappers around' and in this case they come from two different tools in the order bottom to top.

Maybe `fastapi-util` could have 'auto decorated' it but that would mean you can never `@repeat_every` using a different decorator, ie 'after the 20th request'.

FWIW I learned the order (and more) from https://www.youtube.com/watch?v=QH5fw9kxDQA

**Comment by AdityaSoni19031997** [comment] 2024-02-23 10:50
This is not true, you need to trigger the repeatable event on a event loop and then it will start running on it's own. It's mentioned in the docs.

**Comment by yuval9313** [comment] 2024-05-11 15:41
Fixed in #291 and version 0.6.0

**Closed by yuval9313** 2024-05-11 15:41 UTC
Labels: bug

**Comment by imancrsrk** [comment] 2024-05-20 22:30
> Fixed in #291 and version 0.6.0

I'm usinng 0.6.0 and it's not fixed. I can confirm.

**Comment by yuval9313** [comment] 2024-05-21 16:06
Is that not the way you intended? What change you think need to happen?

**Comment by drewmarshburn** [comment] 2024-08-22 20:30
I was not able to use `add_event_handler` to get this to work with the lifespan, but I was able to call the function from within the lifespan.

```
@repeat_every(seconds=1)
def example_repeat():
    print("example")
```

```
async def db_lifespan(app: FastAPI):
    # Db connection...

    # This must be executed on startup (the decorator relies on this being called once to start the loop)
    await example_repeat()

    yield

    # DB close...
```
